#http-method
POST

#url
http://localhost:8080/cycle/calculatePrice

#http-header
@Content-Type: application/json

#request body
[
 {"type":"TUBELESS","cycleComponents":["FRAME","SEAT","RIM"],"dateOfPricing": "2016-05-11"},
 {"cycleComponents":["TUBE","SEAT","RIM"],"dateOfPricing": "2019-08-04"},
 {"cycleComponents":["TYRE","SEAT","RIM"],"dateOfPricing": "2013-06-07"},
 {"cycleComponents":["TUBE","SEAT","RIM"],"dateOfPricing": "2017-08-13"},
 {"cycleComponents":["TYRE","SEAT","RIM"],"dateOfPricing": "2013-07-01"},
 {"type":"TUBELESS","cycleComponents":["FRAME","SEAT","RIM"],"dateOfPricing": "2016-11-30"},
  {"cycleComponents":["TUBE","SEAT","RIM"],"dateOfPricing": "2018-05-01"},
  {"cycleComponents":["TYRE","SEAT","RIM","TYRE"],"dateOfPricing": "2012-05-15"},
  {"cycleComponents":["TUBE","SEAT","RIM"],"dateOfPricing": "2020-04-21"},
  {"cycleComponents":["TYRE","SEAT","RIM"],"dateOfPricing": "2020-02-10"}

]




%%%

# Duration: 31 ms
# URL: http://localhost:8080/cycle/calculatePrice

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sat, 11 Jul 2020 08:49:09 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

[
  {
    "cycleComponentMap": {
      "FRAME": 150.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1306.0
  },
  {
    "cycleComponentMap": {
      "TUBE": 145.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1656.0
  },
  {
    "cycleComponentMap": {
      "TYRE": 200.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1596.0
  },
  {
    "cycleComponentMap": {
      "TUBE": 145.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1656.0
  },
  {
    "cycleComponentMap": {
      "TYRE": 200.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1596.0
  },
  {
    "cycleComponentMap": {
      "FRAME": 150.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1306.0
  },
  {
    "cycleComponentMap": {
      "TUBE": 145.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1656.0
  },
  {
    "cycleComponentMap": {
      "TYRE": 200.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1596.0
  },
  {
    "cycleComponentMap": {
      "TUBE": 145.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1656.0
  },
  {
    "cycleComponentMap": {
      "TYRE": 230.0,
      "SEAT": 94.0,
      "RIM": 151.0
    },
    "priceOfCycle": 1656.0
  }
]